-- HISTORICAL: this schema described the Supabase Postgres backend this project used
-- before every table was moved to static JSON (public/data/ and
-- public/statewise-historical/ - see src/lib/queries.ts and scripts/json_store.py).
-- Nothing reads or writes Supabase anymore; see migration_004_drop_statewise.sql and
-- migration_005_drop_remaining_tables.sql for how the tables themselves were dropped.
-- Kept only as a record of the old column layout.
